config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :delete_all

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    # @review.restaurant = @restaurant
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :find_restaurant

  def new; end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
    # else
    #   render :new
    # end
  end

  private

  def find_restaurant
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_navbar.html.erb
<nav class="navbar navbar-light bg-light justify-content-between px-3">
  <a href="/restaurants" class="navbar-brand">restos</a>
  <a href="/restaurants/new" class="navbar-new-restaurant">Add New Restaurant</a>
</nav>

app/views/restaurants/index.html.erb
<%= render 'navbar' %>

<div class="container">
  <h1>hello this is where all the restaurants should be</h1>

  <ul>
    <% @restaurants.each do |restaurant| %>
      <li><h5><strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong></h5></li>
        <p>Address: <%= restaurant.address %></p>
        <p>Phone: <%= restaurant.phone_number %></p>
        <p>Category: <%= restaurant.category %></p>
        ---
    <% end %>
  </ul>
</div>

app/views/restaurants/new.html.erb
<%= render 'navbar' %>

<div class="container">
  <h1>this is where the user can add a new restaurant</h1>

  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, as: :select, collection: %w[chinese italian japanese french belgian], prompt: 'Select Category' %>
    <%= f.submit "Create Restaurant", class:"btn btn-primary mt-3"%>
  <% end %>

  <%= link_to "Back to all restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<%= render 'navbar' %>

<div class="container">
  <h1>and this is where you see just one restaurant</h1>

  <h5><strong><%= @restaurant.name %></strong></h5>
  <p>Address: <%= @restaurant.address %></p>
  <p>Category: <%= @restaurant.category %></p>

  <h6><strong>Reviews</strong></h6>
    <%  @restaurant.reviews.each do |review| %>
      <div class="card">
        <div class="card-body">
          <p><%= review.content %></p>
          <p>Rating: <%= review.rating %></p>
        </div>
      </div>
    <% end %>

  <!-- <div class="add-review">
    <%= link_to "Add a new review",  new_restaurant_review_path(@restaurant) %>
  </div> -->

  <br>
  <h6><strong>Add a new review</strong></h6>
  <%= render 'reviews/form' %>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, as: :select, collection: %w[0 1 2 3 4 5], prompt: 'Select Rating' %>
  <%= f.input :content %>
  <%= f.submit "Add review", class:"btn btn-primary mt-3"%>
<% end %>

app/views/reviews/new.html.erb
<%= render 'restaurants/navbar' %>

<div class="container">
  <h2>this is for adding a new review to the restaurant</h2>

  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :rating, as: :select, collection: %w[0 1 2 3 4 5], prompt: 'Select Rating' %>
    <%= f.input :content %>
    <%= f.submit "Add review", class:"btn btn-primary mt-3"%>
  <% end %>

  <%= link_to "Back to restaurant", restaurant_path(@restaurant) %>
</div>